### ISSUE TITLE
Spawn obstacle models in gazebo

### ISSUE THREAD

**Issue by bchandaka** [IllinoisRoboticsInSpace/IRIS-2022#2]
- [x] Create an sdf model for a moon rock
- [x] Create a script to spawn a single moon rock at a fixed location
- [x] Check to make sure that rover will collide with obstacles
- [x] Update the script to spawn 3 moon rocks in 3 different, non-colliding locations
_Remember to document important steps!_

**Comment by jgcox2** [comment]
Used this link to set up node to spawn entities: https://zmk5.github.io/general/demo/2019/07/15/ros2-spawning-entity.html
